BaseURL: https://guilhermenovais.sh
title: Guilherme Novais

params:
  description: Terminal Curriculum Vitae 
  prompt: convidado@guilhermenovais.sh
  promptColor: yellow
  exitLocation: about:blank
  greeting: |
    Bem vindo ao meu curriculo terminal 💻
    Digite 'ajuda' para ver os comandos disponíveis
  apresentacao:
    name: Guilherme Novais
    profession: Desenvolvedor de Softwares
    location: Belo Horizonte, MG, Brasil
    email: guilhermenovais.sh@gmail.com
    homelink: https://guilhermenovais.sh/
    description: |
      Olá! Eu me chamo Guilherme, sou desenvolvedor de softwares fascinado por tecnologia e inovação.

      Estou sempre em busca de uma aventura tecnologica para desbravar, tal qual esse próprio site de apresentação em formato de terminal.

      Sinta-se a vontade para conhecer aqui! Ah, e não se esqueça de depois conversar com o meu chatbot, o Constantino. Garanto que será uma experiência bem agradável 🤖
  social:
    - name: github
      url: https://github.com/guiNovais/
    - name: linkedin
      url: https://linkedin.com/in/guilhermenovaisdev/
    - name: instagram
      url: https://instagram.com/guilhermenovais.sh/

  trabalho:
    - jobTitle: Analista de Desenvolvimento de Sistemas
      color: red
      company: Framework Digital
      location: Belo Horizonte, MG
      date: Maio de 2022 - Presente
      description: Atualmente estou alocado dentro do banco Santander, trabalhando com sistemas tanto do antigo Olé Consignado (.NET Core, SQL Server, TFS, Azure, REST, SOAP, Control-M, Dynatrace) quanto com novos sistemas do Santander (Java 17, Spring Boot, Spring Batch, Oracle Database, CloudBees, K8s, OpenShift, SonarQube). Além disso, tive um período alocado na Localiza na qual trabalhei com o desenvolvimento de seu chatbot modelado principalmente com o Blip e utilizando APIs REST.

    - jobTitle: Analista de Sistemas
      color: red
      company: Montreal M.I
      location: Belo Horizonte, MG
      date: Janeiro de 2021 - Maio de 2022
      description: Trabalhei alocado no Banco de Desenvolvimento de Minas Gerais, implementando novas funcionalidades tanto no backend (Java 8, Java EE, Wildfly, Azure) como no aplicativo móvel (React Native) e no portal de atendimento do usuário (Angular).

    - jobTitle: Analista de Sistemas
      color: red
      company: DTI
      location: Belo Horizonte, MG
      date: Fevereiro de 2019 - Setembro de 2019
      description: Fiquei esse período alocado na MRV Engenharia, aonde trabalhei com seu chatbot público para clientes implementado através do IBM Watson Assistant. Sua interação era realizada através tanto de sua interface web própria como através do WhatsApp. Também trabalhei na remodelagem dos sistemas de cálculo do valor de imóveis (.NET Core, Dapper ORM, MediatR, Azure).

    - jobTitle: Desenvolvedor de Softwares
      color: red
      company: HOP
      location: Belo Horizonte, MG
      date: Outubro de 2017 - Fevereiro de 2019 | Setembro de 2019 - December 2020
      description: Trabalhei com sistemas backend orientados para suportar chatbots (Java 8, Spring Boot, IBM Watson Assistant, Facebook Messenger), além da modelagem, construção e curadoria de diversos chatbots, tanto internos quanto públicos. Também atuei na operação das aplicações em nuvem com o IBM Cloud.

    - jobTitle: Intern
      color: red
      company: OneForce
      location: Belo Horizonte, MG
      date: Outubro de 2016 - Outubro de 2017
      description: Trabalhei em um sistema de gerenciamento de recursos para a empresa LB2, com o backend desenvolvido em NodeJS, frontend em AngularJS, banco de dados MongoDB e implantados na nuvem IBM Bluemix.

    - jobTitle: Scholarship holder
      color: red
      company: UniBH & OneForce
      location: Belo Horizonte, MG
      date: Outubro de 2015 - Outubro de 2016
      description: Membro de pesquisa científica-tecnológica na área de processamento de linguagem natural e automação com Arduíno, sob a coordenação dos professores Dr. Moisés Henrique Ramos Pereira e Dr. Felipe Leandro Andrade da Conceição.

    - jobTitle: Intern
      color: red
      company: Rede Minas
      location: Belo Horizonte, MG
      date: Dezembro de 2014 - Deze 2015
      description: Manutenção de hardware e software dos computadores empresariais.

  educacao:
    - courseName: Ciência da Computação - Bacharelado
      color: red
      date: Agosto de 2013 - Agosto de 2017
      description: O curso do UniBH oferece uma base teórica profunda em programação de computadores, matemática e lógica. Os conhecimentos abordados no curso oferecem base e segurança para a formação na área de TI por tempo indeterminado. Aqui houve o contato com os principais recursos TI, como banco de dados, redes de computadores, inteligência artificial, compiladores, engenharia de software, entre outros.

  habilidades:
    - name: Desenvolvimento Backend
      color: aqua
      percentage: 90
      description: Java versões 8, 11 e 17 | Spring Boot | Spring Batch | Java EE | C# | .NET Core | TypeScript | AdonisJS

    - name: Operação e Sustentação
    

    - name: Inteligência Artificial
      color: aqua
      percentage: 75
      description: Chatbots com IBM Watson e Blip

    - name: Computação em Nuvem
      color: aqua
      percentage: 50
      description: AWS | IBM Cloud

    - name: Desenvolvimento Frontend
      color: aqua
      percentage: 40
      description: React Native | Angular

  softskills:
    - name: Curiosidade
      color: aqua
      percentage: 100
      description: Sempre estou a procura de novas formas de interagir com tecnologia buscando recursos que fogem do que é rotineiro. Isso me proporciona o contato com vários aspectos das ferramentas de desenvolvimento, seja em questão de linguagem de programação, estratégias de modelagem de sistemas, planejamento e curadoria de assistentes virtuais, etc.

    - name: Trabalho em equipe
      color: aqua
      percentage: 80
      description: Ao planejar e elaborar uma solução, eu busco ao máximo a contribuição e opinião dos meus colegas de trabalho. Acredito que ao passar pela análise crítica de várias pessoas, conseguimos um grande valor em questão de qualidade do produto final. Além disso, eu vejo como os envolvidos se tornam mais engajados e exigentes com a qualidade de todas as entregas.

    - name: Comunicação
      color: aqua
      percentage: 75
      description: Trabalhar com tecnologia exige a capacidade de se comunicar de maneira bastante assertiva com pessoas de diferentes áreas, seja de negócio, seja técnico. É justamente isso o que permite a elaboração de soluções eficientes, escaláveis e de fácil manutenção.

    - name: Liderança
      color: aqua
      percentage: 60
      description: Acredito que liderar exige um grande conhecimento e capacidade de imersão sobre o trabalho de cada membro de uma equipe. Sendo assim, acredito que as minhas características de liderança se encontram orientadas para equipes técnicas e de desenvolvimento, pois é justamente nesse lugar em que eu tenho mais engajamento e conhecimento para direcionar os eforços de cada membro para soluções de alta qualidade.

  idiomas:
    - name: Inglês
      color: red
      percentage: 70
      #description:

    - name: Português
      color: lime
      percentage: 100
      # description:

  certificacoes:
    - certName: Oracle Certified Associate, Java SE 8 Programmer
      company: Oracle
      date: April 2023
      description: An Oracle Certified Associate, Java SE 8 Programmer has demonstrated knowledge of object-oriented concepts, the Java programming language and general knowledge of Java platforms and technologies.

    - certName: IBM Certified Application Developer - Watson V3 Certification
      company: IBM Professional Certification
      date: December 2017
      description: This intermediate level technical professional is an individual who understands concepts essential to the development of applications using IBM Watson AI services. They will have experience using the IBM Cloud and are able to consume IBM Watson AI services in an application. This individual is able to perform these tasks with little to no assistance from product documentation, support or peers.
